vector.h done
Borodin239/first-term pull request #1
Opened 2020-06-19 20:49 UTC by Borodin239

2020-06-20 10:21 UTC, kt-cpp requested changes
Оставил замечания, повторные ошибки комментировать не стал, найди их пожалуйста сам

2020-06-20 10:21 UTC, kt-cpp commented on vector/vector.h
> +    T temp = val;
[warning] Переменная не используется. Читайте ворнинги компилятора

2020-06-20 10:21 UTC, kt-cpp commented on vector/vector.h
> +    }
[semantic] деструкторы лучше вызывать в обратном порядке от конструкторов.

2020-06-20 10:21 UTC, kt-cpp commented on vector/vector.h
> +    assert(i < size_);
[semantic] ассертить "продовый код" можно только в тех местах, где эта гарантия нужна разработчику библиотеки (проверка что его код соблюдает собственные инварианты), а не в тех инвариантах, которые легко может нарушить пользователь библиотеки. Ассерты не контролируются, значит вызов этого метода некорректно будет крашить всю программу -- очень грубое, недопустимое поведение для библиотеки

2020-06-20 10:21 UTC, kt-cpp commented on vector/vector.h
> +    assert(new_capacity >= size_);
[note] Вот это **корректное** использование ассертов

2020-06-20 10:21 UTC, kt-cpp commented on vector/vector.h
> +    }
[semantic] Здесь тоже порядок деструкций

2020-06-20 10:21 UTC, kt-cpp commented on vector/vector.h
> +    }
[duplicate] почему бы не использовать `clear()`?

2020-06-20 10:21 UTC, kt-cpp commented on vector/vector.h
> +    swap(temp);
[semantic] Это не работает так как должно, `swap` не укорачивает буфер

2020-06-20 10:21 UTC, kt-cpp commented on vector/vector.h
> +    assert(i < size_);
У тебя еще много таких мест, пожалуйста, найди все, чтобы я не комментировал каждое

2020-06-20 10:21 UTC, kt-cpp commented on vector/vector.h
> +    }
Порядок деструкторов много где неверный, проверь, пожалуйста, все места

2020-06-20 10:21 UTC, kt-cpp commented on vector/vector.h
> +    for (int i = from; i < size_ - delta; i++) {
[overhead] `size - delta = size - to + from = size - last + data + first - data = size - last + first = size - (last - first)`

2020-06-20 10:21 UTC, kt-cpp commented on vector/vector.h
> +    int from = first - data_;
[semantic] Некорректный тип, нужен - `ptrdiff_t`. Проверь всю эту функцию

2020-06-20 11:12 UTC, kt-cpp commented on vector/vector.h
> +vector<T>::vector() {
Здесть еще можно сделать `default` или использовать `member initializer list`

2020-07-05 20:04 UTC, kt-cpp requested changes
нужно фиксить + добавить новые тесты. и у тебя почему то диф в файле тестов, так не надо

2020-07-05 20:04 UTC, kt-cpp commented on vector/vector.h
> +        data_[i] = data_[i - 1];
копирование вместо свапа

2020-07-05 20:04 UTC, kt-cpp commented on vector/vector.h
> +    new(data_ + size_) T();
Т не обязан иметь такой конструктор, лучше уж сразу push_back(val)

2020-07-05 20:04 UTC, kt-cpp commented on vector/vector.h
> +void vector<T>::clear_elements() {
сделай это статик функцией, которая принимает указатель и количество элементов на удаление. количество копипасты снизится

2020-07-05 20:04 UTC, kt-cpp commented on vector/vector.h
> +    this->~vector();
вызывать свой деструктор это плохо

2020-07-05 20:04 UTC, kt-cpp commented on vector/vector.h
> +        for (; i < other.size(); i++) {
копипаста с new_buffer

2020-07-05 20:04 UTC, kt-cpp commented on vector/vector.h
> +    if (capacity_ == 0) {
такой же блок в push_back_realloc. вынеси в общий метод

2020-07-05 20:04 UTC, kt-cpp commented on vector/vector.h
> +vector<T>::vector() : capacity_(0), size_(0), data_(0) {}  // Применил member initializer list
неверный порядок, из-за чего коимпилятор кидает ворнинг. + ты кладешь в указатель 0

2020-07-06 10:18 UTC, Borodin239 commented
Изначально запушил с одной утечкой по памяти, через пару часов обнаружил её и исправил (добавилась одна строка в коммите  find a problem). Все основные изменения кроме этого были сделаны в последнем коммите fixed

2020-07-06 18:16 UTC, kt-cpp requested changes
минорные design проблемы

2020-07-06 18:16 UTC, kt-cpp commented on vector/vector.h
> +void vector<T>::clear_elements(int32_t from, int32_t count) {
вместо size_t стоят инты + сделать статик функцией, принять доп аргументов указатель где нужно чистить. поставить это в new_buffer()

2020-07-06 18:16 UTC, kt-cpp commented on vector/vector.h
> +            new(new_data + i) T(data_[i]);
на вкус копипаста копиконструктора. весь кусок с аллоцированием и копированием в новый буффер можно вынести в отдельный метод. ну или мб ты как-то еще лучше придумаешь

2020-07-06 18:17 UTC, kt-cpp commented
+ у тебя проблемы с гитом: "This branch cannot be rebased due to conflicts"

2020-07-07 05:51 UTC, Borodin239 commented
Все ошибки, которые касаются кода, я исправил.
По поводу гита: я вначале сам пытался решить эти конфликты, потом мы с Денисом Воркожоковым потратили ещё час на эту проблему, на моём мастере откатили назад два коммита, чтобы убрать изменения в main.cpp и в ещё одном файле с тестами. Под конец уже в тупую в ветку vector руками положили исходные main.cpp и файл из big int, в котором был конфликт, -- ничего не помогло. При этом гит мне спокойно даёт сделать merge pull request. В итоге Глеб разрешил эту проблему не фиксить и сконцентрироваться на коде. Как следствие всех этих попыток -- лишние пробелы в тестах устранены

2020-07-07 17:16 UTC, kt-cpp approved these changes

2020-07-07 17:16 UTC, kt-cpp commented on vector/vector.h
> +void vector<T>::clear_elements(size_t from, size_t count, T* ptr) {
[note] обычно численные константы ставят в конце

2020-07-07 17:16 UTC, merged