Mul fixed
Borodin239/first-term pull request #2
Opened 2020-07-02 14:23 UTC by Borodin239

2020-07-02 20:11 UTC, kt-cpp commented on asm/mul.asm
> +        push        rcx
Неправильный порядок `push`, `pop` сбивает с толку. Надо это переписать.

2020-07-02 20:11 UTC, kt-cpp commented on asm/mul.asm
> +;    r11 -- length of long numbers in qwords (129)
`r14`?

2020-07-02 20:13 UTC, kt-cpp commented on asm/mul.asm
> +        sub         rsp, 5 * 128 * 8 + 8 * 4	; rsp - stack-pointer, указывает на место, где справа всё полезное и писать нельзя, а слева пусто
128 * 8 * 2 под числа
128 * 8 * 2 под ответ
128 * 8  + 8 под грязные вычисления
8 * 2 под лишний байтик для чисел
А еще 8 зачем?

2020-07-02 20:14 UTC, kt-cpp commented on asm/mul.asm
> +		ret
Ты можешь обойтись без копирования обратно, если на каждой итерации будешь копировать и умножать (перезатирая предыдущую операцию)

2020-07-02 20:15 UTC, kt-cpp requested changes
Так-то хорошо, но хочется немного лучше

Комменты :+1:

2020-07-03 13:08 UTC, kt-cpp commented on asm/mul.asm
> +;    product is written to rdi
`mul_long_short` теперь имеет эффект записи за память отведенную под это число (если рассчитывать что памяти выделено rcx * 8). Хорошо бы в контракте это указать

2020-07-03 13:09 UTC, kt-cpp approved these changes
Пойдет

2020-07-03 13:09 UTC, merged

2020-07-03 14:59 UTC, Borodin239 commented on asm/mul.asm
> +;    product is written to rdi
Хорошо, я понял, но я специально для этих целей выделял на один бит больше чем rcx. Сейчас в master подправлю комментарии