Bigint
Borodin239/first-term pull request #3
Opened 2020-07-08 15:01 UTC by Borodin239

2020-07-08 17:22 UTC, kt-cpp requested changes

2020-07-08 17:22 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    }
То есть "-00" уже будет отрицательный? Постарайтесь эту проблему решить без костыля

2020-07-08 17:22 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    }
Это бы объединить, код почти одинаковый

2020-07-08 17:22 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    d.is_negative_ = false;
Можно написать abs

2020-07-08 17:22 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        }
while (digits.size > 1 && digits.back == 0) pop_back()
такая идея намного проще

2020-07-08 19:46 UTC, Borodin239 commented on bigint/big_integer.cpp
> +        }
Аргумент, однако, спасибо)

2020-07-09 07:57 UTC, kt-cpp approved these changes

2020-07-09 07:57 UTC, merged